CrashCourse/03_-_web_app/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learnings_app.urls')),
]

CrashCourse/03_-_web_app/learnings_app/urls.py
from django.urls import path

from . import views

app_name = 'learnings_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

CrashCourse/03_-_web_app/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

CrashCourse/03_-_web_app/learnings_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

CrashCourse/03_-_web_app/users/models.py
from django.db import models

# Create your models here.

CrashCourse/03_-_web_app/learnings_app/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text'] # solo el 'text field'
        labels = {'test': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'} # a blank label
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

CrashCourse/03_-_web_app/learnings_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    return render(request, 'learning_log/index.html')


@login_required
def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_log/topics.html', context)


@login_required
def topic(request, topic_id):
    topic = get_object_or_404(Topic, id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_log/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        # No data enviado; crea un blank form
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.user = request.user
            new_topic.save()
            return redirect('learnings_app:topics')
    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'learning_log/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learnings_app:topic', topic_id=topic_id)

    context = {'topic': topic,
               'form': form}

    return render(request, 'learning_log/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learnings_app:topic', topic_id=topic.id)

    context = {'entry': entry,
               'topic': topic,
               'form': form}

    return render(request, 'learning_log/edit_entry.html', context)

CrashCourse/03_-_web_app/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learnings_app:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

CrashCourse/03_-_web_app/learnings_app/templates/learning_log/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Polu blog</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <a class="navbar-brand" href="{% url 'learnings_app:index'%}">Polu blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarCollapse" aria-controls="navbarCollapse"
              aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learnings_app:topics'%}">Topics</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text">Hello, {{ user.username }}.</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
            </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <!-- <p>
      <a href="{% url 'learnings_app:index' %}">Learning Log</a> -
      <a href="{% url 'learnings_app:topics' %}">Topics</a> -
      {% if user.is_authenticated %}
        Hola, {{ user.username }}
        <a href="{% url 'users:logout' %}">Log out</a>
        {% else %}
      <a href="{% url 'users:register' %}">Registrarse</a>
      <a href="{% url 'users:login' %}">Ingresar</a>
      {% endif %}
    </p> -->
    <main role="main" class="container">
      <div>{% block content %} {% endblock content %}</div>
    </main>

  </body>
</html>

CrashCourse/03_-_web_app/learnings_app/templates/learning_log/edit_entry.html
{% extends "learning_log/base.html" %} {% block content %}

<p><a href="{% url 'learnings_app:topic' topic.id %}">{{ topic }}</a></p>
<p>Editar entrada:</p>
<form action="{% url 'learnings_app:edit_entry' entry.id %}" method="post">
  {% csrf_token %} {{ form.as_p }}
  <button name="submit">Modificar entrada</button>
</form>

{% endblock content %}

CrashCourse/03_-_web_app/learnings_app/templates/learning_log/index.html
{% extends "learning_log/base.html" %}
{% block content %}
    <p>PeePee</p>
    <h1>Palabras más, palabras menos</h1>
{% endblock content %}

CrashCourse/03_-_web_app/learnings_app/templates/learning_log/new_entry.html
{% extends "learning_log/base.html" %}
{% block content %}

<p><a href="{% url 'learnings_app:topic' topic.id %}">{{ topic }}</a></p>
<p>Nueva entrada: </p>
<form action="{% url 'learnings_app:new_entry' topic.id %}" method='post'>
 {% csrf_token %}
 {{ form.as_p }}
 <button name='submit'>Add entry</button>
</form>

{% endblock content %}

CrashCourse/03_-_web_app/learnings_app/templates/learning_log/new_topic.html
{% extends "learning_log/base.html" %}
{% block content %}
<p>Add a new topic:</p>
<form action="{% url 'learnings_app:new_topic' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">Add topic</button>
 </form>

 {% endblock content %}

CrashCourse/03_-_web_app/learnings_app/templates/learning_log/topic.html
{% extends 'learning_log/base.html' %} {% block content %}
<h3>Topic: {{ topic }}</h3>
<p>Entries:</p>
<p>
  <a href="{% url 'learnings_app:new_entry' topic.id %}">Add new entry</a>
</p>

  {% for entry in entries %}

    <div class="card mb-3">
      <h4 class="card-header">
      {{ entry.date_added|date:'M d, Y H:i' }}
      <small><a href="{% url 'learnings_app:edit_entry' entry.id %}">Edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>

  {% empty %}
  <li>No hay entradas</li>
  {% endfor %}

{% endblock content %}

CrashCourse/03_-_web_app/learnings_app/templates/learning_log/topics.html
{% extends "learning_log/base.html" %}
{% block content %}
<p>Topics</p>
<ul>
  {% for topic in topics %}

   <li><h3>
     <a href="{% url 'learnings_app:topic' topic.id %}">{{ topic }}</a>
   </h3></li>
  {% empty %}
    <li><h3>No topics</h3></li>
  {% endfor %}
</ul>

<h3><a href="{% url 'learnings_app:new_topic' %}">Nuevo topic</a></h3>


{% endblock content %}